# -*- coding: utf-8 -*-
"""game.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Wx3cG9CdvJZOAnDhU1rEkv3fYRwDrGAb
"""

print("welcome to the rock,paper,scissor game")

import random

user_choice=int(input("what should u like to choose?Select 0 for rock,1 for paper and 2 for scissor.\n"))
computer_choice=random.randint(0,2)
print(f"computer choose {computer_choice}")
if  user_choice>=3 or user_choice<0:
    print("invalid number.please choose again")
elif user_choice==0 and computer_choice==2:
    print("you win")
elif computer_choice==0 and user_choice==2:
    print("you lose")
elif computer_choice>user_choice:
    print("you lose")
elif user_choice>computer_choice:
    print("you win")
elif computer_choice==user_choice:
    print("its a tie")